# Kubernetes App Docker image build for hub.docker.com
name: Maverick sales CI

# Run this Build for all pushes to 'main' branch, or tagged releases.
on:
  push:
    branches:
      - maverick-sales

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env: 
  SHORT_SHA: $(echo ${{ github.sha }} | cut -c 1-8)

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout codebase
        uses: actions/checkout@v3.3.0

      # https://github.com/docker/setup-buildx-action
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      # https://github.com/docker/login-action
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build, tag, and push image to Docker hub
        id: build-image
        run: |
          docker image build \
          --tag ${{ secrets.DOCKER_USERNAME }}/maverick_user:v1 \
          --tag ${{ secrets.DOCKER_USERNAME }}/maverick_user:${{ env.SHORT_SHA }} \
          .
          docker push ${{ secrets.DOCKER_USERNAME }}/maverick_user:v1
          docker push ${{ secrets.DOCKER_USERNAME }}/maverick_user:${{ env.SHORT_SHA }}      